name: Generate Datas

on:
  schedule:
    - cron: "0 0 * * *"  # Executa à meia-noite (UTC)
    - cron: "0 10 * * *" # Executa às 10h (UTC)
    - cron: "0 16 * * *" # Executa às 16h (UTC)

  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório para permitir salvar arquivos gerados
      - name: Check out repository
        uses: actions/checkout@v2

      # Gera a animação da cobrinha
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: mariaandrezacs
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-light.svg?palette=github

      # Commit e push da animação gerada
      - name: Commit and Push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-snake*.svg
          git commit -m "Atualiza snake animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
