name: Generate Datas

on:
  schedule:
    # Executa uma vez por dia
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Baixa uma ação para gerar a animação
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: mariaandrezacs
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-light.svg?palette=github
