name: Generate Datas

on:
  schedule:
    # - cron: "0 0 * * *"  # Executa à meia-noite (UTC)
    # - cron: "0 10 * * *" # Executa às 10h (UTC)
    # - cron: "0 16 * * *" # Executa às 16h (UTC)
    # - cron: "0 */4 * * *" # Executa a cada 4h (UTC)
    - cron: "0 */2 * * *" # Executa a cada 2h (UTC)

  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório para permitir salvar arquivos gerados
      - name: Check out repository
        uses: actions/checkout@v4

      # Gera a animação da cobrinha
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: mariaandrezacs
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-light.svg?palette=github

      # Atualiza o cache do GitHub Stats
      - name: Update GitHub Stats cache
        shell: bash
        run: |
          VERSION=$(date -u +"%Y%m%d%H%M%S")
      
          sed -i -E \
            "s/(&v=)[^&\"]*/\1${VERSION}/g" \
            README.md
      
          echo "GitHub Stats cache version: ${VERSION}"

      # Commit e push da animação gerada
      - name: Commit and Push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-snake*.svg
          git diff --cached --quiet || (git commit -m "Atualiza snake animation" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
